spring.application.name=picketf
spring.thymeleaf.cache=false

spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

server.port=${PORT:8080}

# --- KRX ETF 일별매매정보 ---
krx.api.base-url=https://data-dbg.krx.co.kr
krx.api.path=/svc/apis/etp/etf_bydd_trd

krx.api.debug=true

# Authorization 헤더 방식 (Bearer {키})
krx.api.auth.type=header
krx.api.auth.header-name=Authorization
krx.api.auth.header-format=Bearer %s

# 타임아웃
http.client.connect-timeout=3000
http.client.read-timeout=5000

# Spring Security crsf 디버그 로그
logging.level.org.springframework.security=DEBUG