spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.jdbc-url=${DB_URL}

twelvedata.api.key=${TWELVEDATA_API_KEY}
krx.api.key=${KRX_API_KEY}

security.rememberme.key=${REMEMBER_ME_KEY}