spring.application.name=picketf
spring.thymeleaf.cache=false

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.jdbc-url=${DB_URL}

security.rememberme.key=longtimenosee
twelvedata.api.key=${TWELVEDATA_API_KEY}
krx.api.key=${KRX_API_KEY}

# --- KRX ETF 일별매매정보 ---
krx.api.base-url=${KRX_API_BASE_URL}
krx.api.path=${KRX_API_PATH}

krx.api.debug=true

# Authorization 헤더 방식 (Bearer {키})
krx.api.auth.type=header
krx.api.auth.header-name=Authorization
krx.api.auth.header-format=Bearer %s

# 타임아웃
http.client.connect-timeout=3000
http.client.read-timeout=5000

# Spring Security crsf 디버그 로그
logging.level.org.springframework.security=DEBUG

# 도커 배포
server.port=${PORT:8080}